version: '3.4'

volumes:
  keycloak:

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    environment:
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --fail --silent http://localhost:8080/health/ready 2>&1 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      -  ./testdata/gocloak-realm.json:/opt/keycloak/data/import/gocloak-realm.json
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev --import-realm"]

